language: java
jdk:
  - oraclejdk7
before_install:
 - chmod +x gradlew
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c620e84679284b7d621
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
Your unique webhook url for this service: